### ISSUE TITLE
Confusing README and lack of "sync" functions

### ISSUE THREAD

**Issue by robross0606** [simonlast/node-persist#147]
All the available functions are `async` and the README has this example:
```js
const storage = require('node-persist');

//you must first call storage.init
await storage.init( /* options ... */ );
await storage.setItem('name','yourname')
console.log(await storage.getItem('name')); // yourname
```

The `package.json` file `engine` declares `"node": ">=10.12.0"` but the example doesn't jive because you could not use `await` on a top-level module until after Node v14.8 and only in ES Modules.  Therefore, the example is at the very least misleading since it is using CommonJS `require()` along with top-level `await` which isn't really feasible AFAIK.

Tracing through the code base, especially `init()` appears to be `async` purely because the non-"sync" versions of `fs` tools were used for [`ensureDirectory()`](https://github.com/simonlast/node-persist/blob/master/src/local-storage.js#L252).  

It would be very beneficial towards flexible usage if an `initSync()` method were added which used the "sync" versions of `fs` tooling to provide a blocking version of the function where we cannot use `await`:

- [fs.accessSync()](https://nodejs.org/api/fs.html#fsaccesssyncpath-mode)
- [fs.mkdirSync()](https://nodejs.org/api/fs.html#fsmkdirsyncpath-options)

This could then be used in more locations, such as in constructors and top-level modules where `await` is impossible.

**Comment by akhoury** [comment]
You are right. I re-added `initSync`, use v[4.0.1](https://www.npmjs.com/package/node-persist/v/4.0.1)

Thank you

**Comment by QuentinNev** [comment]
I'm using v4.0.1 and doing this :
`const storage = require('node-persist');
storage.initSync();`

Throws this error : TypeError: storage.initSync is not a function

**Comment by teldosas** [comment]
@QuentinNev it looks like you need to do something like this now:

```javascript
const nodePersist = require('node-persist')
const storage = nodePersist.create()
storage.initSync()
```

(from the [tests](https://github.com/simonlast/node-persist/blob/fc90737f80baf12753bb12367ac09a8ecfef8e97/tests/index.js))

**Comment by akhoury** [comment]
Thanks @teldosas you're right, but i just added initSync on the default instance, @QuentinNev your code should work with 4.0.3
